public enum ElementalReaction
{
    MeltStrong,
    MeltWeak,
    VaporizeStrong,
    VaporizeWeak,
    ElectroCharged,
    Overloaded,
    Superconduct,
    Freeze,
    SwirlPyro,
    SwirlCryo,
    SwirlHydro,
    SwirlElectro,
    CrystallizePyro,
    CrystallizeCryo,
    CrystallizeHydro,
    CrystallizeElectro
}